// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi9ZaZ_G5wGDZQacOFPEjmdW1QHcxx-Ko',
    appId: '1:409068026931:web:897c2cdbfecf60484e7746',
    messagingSenderId: '409068026931',
    projectId: 'task-manager-app-86e9d',
    authDomain: 'task-manager-app-86e9d.firebaseapp.com',
    storageBucket: 'task-manager-app-86e9d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvCDUFWCup_z3RGvthCfmGBXRITrJs8MM',
    appId: '1:409068026931:android:dcec211b4fd91ac44e7746',
    messagingSenderId: '409068026931',
    projectId: 'task-manager-app-86e9d',
    storageBucket: 'task-manager-app-86e9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCdBhIR84_hdTp8_TV8Q-i2M4UMyhHGKI',
    appId: '1:409068026931:ios:57698138940513504e7746',
    messagingSenderId: '409068026931',
    projectId: 'task-manager-app-86e9d',
    storageBucket: 'task-manager-app-86e9d.firebasestorage.app',
    iosBundleId: 'com.assignment4.NLA.assignment4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCdBhIR84_hdTp8_TV8Q-i2M4UMyhHGKI',
    appId: '1:409068026931:ios:57698138940513504e7746',
    messagingSenderId: '409068026931',
    projectId: 'task-manager-app-86e9d',
    storageBucket: 'task-manager-app-86e9d.firebasestorage.app',
    iosBundleId: 'com.assignment4.NLA.assignment4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBi9ZaZ_G5wGDZQacOFPEjmdW1QHcxx-Ko',
    appId: '1:409068026931:web:016ba824a8d614db4e7746',
    messagingSenderId: '409068026931',
    projectId: 'task-manager-app-86e9d',
    authDomain: 'task-manager-app-86e9d.firebaseapp.com',
    storageBucket: 'task-manager-app-86e9d.firebasestorage.app',
  );
}
